Jamhuri/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('schapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schapp/urls.py
from django.urls import path
from . import views

app_name = 'schapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('departments/', views.departments, name='departments'),
    path('clubs/', views.clubs, name='clubs'),
    path('sports/', views.sports, name='sports'),


]

schapp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Staff(models.Model):
    name = models.CharField(max_length=30)
    position = models.CharField(max_length=20)
    staff_img = models.FileField()
    staff_desc = models.TextField()

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=30)
    desc = models.TextField()
    date = models.DateField()
    image = models.FileField()

    def __str__(self):
        return self.title


class Department(models.Model):
    name = models.CharField(max_length=30)
    hod = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.name


class Club(models.Model):
    name = models.CharField(max_length=30)
    patron = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.name


class Mission(models.Model):
    title = models.CharField(max_length=20)
    desc = models.TextField()

    def __str__(self):
        return self.title


class Vision(models.Model):
    title = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.title


class Anthem(models.Model):
    title = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.title


class Motto(models.Model):
    title = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=45)
    date = models.DateField(default=timezone.now)
    image = models.FileField()
    content = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=1)
    date = models.DateField(default=timezone.now)
    comment = models.TextField()

    def __str__(self):
        return self.comment


class Message(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return self.subject


class Coach(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):
        return self.name


class Sport(models.Model):
    coach = models.ForeignKey(Coach, on_delete=models.PROTECT)
    name = models.CharField(max_length=40)
    desc = models.TextField(default=1)

    def __str__(self):
        return self.name

schapp/views.py
from django.shortcuts import render
from . models import Staff, Event, Sport, Department, Club, Mission, Vision, Anthem, Motto, Post


# Create your views here.
def index(request):
    staffs = Staff.objects.all()
    events = Event.objects.all()
    clubs = Club.objects.all()
    missions = Mission.objects.all()
    visions = Vision.objects.all()
    anthems = Anthem.objects.all()
    mottos = Motto.objects.all()
    posts = Post.objects.all()

    context = {
           'staffs': staffs,
           'events': events,
           'clubs': clubs,
           'missions': missions,
           'visions': visions,
           'anthems': anthems,
           'mottos': mottos,
           'posts': posts
               }
    return render(request, 'schapp/index.html', context)


def departments(request):
    dpars = Department.objects.all()
    return render(request, 'schapp/departments.html', {'dpars': dpars})


def clubs(request):
    cbs = Club.objects.all()
    return render(request, 'schapp/clubs.html', {'cbs': cbs})


def sports(request):
    games = Sport.objects.all()
    return render(request, 'schapp/sports.html', {'games': games})















schapp/templates/schapp/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'schapp/css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'schapp/css/style.css' %}" type="text/css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 </head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'schapp:index' %}">Jamhuri High</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li> <a href=""><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Home</a></li>

            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'schapp:departments' %}">
                        <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp; Departments
                    </a>
                </li>

                <li>
                    <a href="{% url 'schapp:clubs' %}">
                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>&nbsp; Clubs
                    </a>
                </li>

                <li>
                    <a href="{% url 'schapp:sports' %}">
                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp; Sports
                    </a>
                </li>

                <li>
                    <a href="">
                        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp; Gallery
                    </a>
                </li>



            </ul>
        </div>

    </div>
</nav>

{% block content %}

{% endblock %}
</body>
</html>

schapp/templates/schapp/clubs.html
{% extends 'schapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
    <div class="banner-img">
    <img src="{% static 'schapp/img/depart.jpg' %}" alt="" style="width: 100%; padding-top: 30px; height: 40%;">

        <div class="page-header">
            <h1 class="text-center text-primary"> <strong>Clubs</strong></h1>
        </div>
    </div>
</div>

    <br>
        {% if cbs %}
            {% for c in cbs %}
    <div class="col-sm-3">
        <div class="panel panel-primary">
            <div class="" style="padding-left: 18px;">
                <h3>{{ c.name }}</h3>
                <p>{{ c.patron }}</p>
            </div>
            <div class="panel-body">
                <p>{{ c.desc }}
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" style="margin: 4px;">More</button>

                <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="padding:5px 5px;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="text-center" style="color: darkslategrey;"><b>{{ c.name }}</b></h4>


                                </div>
                                <div class="modal-body" style="padding:40px 5px;">
                                    <p>{{ c.desc }}</p>
                                </div>

                            </div>

                        </div>
                    </div>
            <!--End Modal-->

            </div>
        </div>
    </div>
            {% endfor %}
    {% endif %}
    </div>
    <script src="{% static 'schapp/js/main.js' %}"></script>
    {% include 'schapp/footer.html' %}

{% endblock %}

schapp/templates/schapp/departments.html
{% extends 'schapp/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'schapp/css/main.css' %}" type="text/css">
{% block content %}
    <div class="container-fluid">
    <div class="row">
    <div class="banner-img">
    <img src="{% static 'schapp/img/jahmu.jpg' %}" alt="" style="width: 100%; padding-top: 30px; height: 40%;">
        <div class="page-header">
            <h1 class="text-center text-primary"> <strong>Departments</strong></h1>
        </div>
    </div>
</div>

        <br>

        {% if dpars %}
            {% for d in dpars %}
    <div class="col-sm-3">
        <div class="panel panel-primary">
            <div class="" style="padding-left: 18px;">
                <h3>{{ d.name }}</h3>
                <p>{{ d.hod }}</p>
            </div>
            <div class="panel-body">
                <p>{{ d.desc }}</p>
            </div>
        </div>
    </div>
            {% endfor %}
    {% endif %}


    </div>


    {% include 'schapp/footer.html' %}

{% endblock %}

schapp/templates/schapp/footer.html
   <!-- Footer section -->
   <div class="container-fluid">
    <div class="row">
    <div class="page-footer" style="width: 100%; height: 40%; background-color: black; color: cadetblue;">
        <br>
        <div class="text-center">
        <h2 class="text-center"><strong>Jamhuri High School</strong></h2>
            <h4 class="text-center">Nairobi</h4>
            <h5 class="text-center">+254 723 494 571</h5>
            <div class="social-media">
                <center>
                	<br><br>
                    <table>
                        <tr>
                            <td><a href="mailto:kimeualexis@gmail.com" target="_blank"><i class="fa fa-envelope fa-3x" style="margin: 10px; color: grey;"></i></a></td>
                            <td><a href="https://github.com/kimeualexis" target="_blank"><i class="fab fa-facebook fa-3x" style="margin: 10px; color: grey;"></i></a></td>
                            <td><a href="https://twitter.com/kodenaut" target="_blank"><i class="fab fa-twitter fa-3x" style="margin: 10px; color: grey;"></i></a></td>
                            <td><a href="https://twitter.com/kodenaut" target="_blank"><i class="fab fa-instagram fa-3x" style="margin: 10px; color: grey;"></i></a></td>
                        </tr>
                    </table>
                </center>
            </div>
        </div>


        <div class="copyright text-center" style="padding-top: 1px;
        font-weight: 600;
        font-size: 18px;
        text-shadow: none;">
            © Jamhuri High 2019
        </div>

    </div>
    </div>
   </div>

schapp/templates/schapp/index.html
{% extends 'schapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="banner-img">
    <img src="{% static 'schapp/img/jahmu.jpg' %}" alt="" style="width: 100%; padding-top: 30px;">
    </div>
</div>

<div class="container-fluid">

<!-- About Section -->
<div class="row">
    <br>

    {% for m in missions %}
    <div class="col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="text-primary"><i class="fa fa-graduation-cap"></i>
                    {{ m.title }}
                </h3>
            </div>
            <div class="panel-body" style="height: 20%;">
                <p>{{ m.desc }}</p>
            </div>
        </div>
    </div>
    {% endfor %}

{% for v in visions %}
    <div class="col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="text-primary"><i class="fa fa-balance-scale"></i>
                    Vision
                </h3>
            </div>
            <div class="panel-body" style="height: 20%;">
                <p>{{ v.desc }}</p>
            </div>
        </div>
    </div>
{% endfor %}


{% for a in anthems %}
    <div class="col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="text-primary"><i class="fa fa-male"></i>
                    Anthem
                </h3>
            </div>
            <div class="panel-body" style="height: 20%;">
                <p>{{ a.desc }}</p>
            </div>
        </div>
    </div>
{% endfor %}


{% for m in mottos %}
    <div class="col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="text-primary"><i class="fa fa-school"></i>
                    Motto
                </h3>
            </div>
            <div class="panel-body" style="height: 20%;">
                <p>{{ m.desc }}</p>
            </div>

        </div>
    </div>
{% endfor %}
</div>


    <!-- End of About -->

       <!-- Staff section -->
    <div class="row">
        <div class="page-header">
            <h3 class="text-center text-primary text-head"><b>Our Staff</b></h3>
        </div>

        {% for staff in staffs %}
        <div class="col-md-3">
            <img src="{{ staff.staff_img.url }}" class="img img-responsive img img-circle" alt="" style="height: 200px; width: 200px;">
            <div class="staff-text">
                <hr>
                <h4 class="text-primary">{{ staff.name }}</h4>
                <h5 class="text-primary">{{ staff.position }}</h5>
                <br>
                <p>{{ staff.staff_desc }}</p>
                <hr>
            </div>
        </div>

        {% endfor %}

    </div>
    <!-- End of Staff -->

    <!-- Events -->
    <div class="row">
        <div class="page-header">
            <h3 class="text-primary text-center text-head"><b>Events</b></h3>
        </div>

        {% if events %}
            {% for event in events %}
        <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-body">
                <img src="{{ event.image.url }}" alt="" class="img img-thumbnail" style="height: 250px; width: 250px;">
                <hr>
                <h3 class="text-primary">{{ event.title }} <small class="text-primary" style="float: right;">Date: {{ event.date }}</small></h3>
                <p>{{ event.desc }}</p>
            </div>
            <div style="padding-left: 10px;">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" style="margin: 4px;">More</button>
            </div>

            <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="padding:5px 5px;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="text-center" style="color: darkslategrey;"><b>Title</b></h4>


                                </div>
                                <div class="modal-body" style="padding:40px 5px;">
                                    <p>
                                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </p>
                                </div>

                            </div>

                        </div>
                    </div>
            <!--End Modal-->

        </div>
        </div>
            {% endfor %}
        {% endif %}



    </div>

    <!-- End of Events -->


    <!-- Blog section -->
    <div class="row">
        <div class="page-header">
            <h3 class="text-center text-primary text-head"><b>Blog</b></h3>
        </div>

        {% if posts %}
        {% for post in posts %}
        <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-body">
                <img src="{{ post.image.url }}" alt="" class="img img-thumbnail" style="height: 250px; width: 328px;">
                <hr>
                <h3 class="text-primary">{{ post.title }} <small class="text-primary" style="float: right;">Date: {{ post.date }}</small></h3>
                <p>{{ post.content }}</p>
            </div>
            <div style="padding-left: 10px;">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" style="margin: 4px;">More</button>
            </div>

            <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="padding:5px 5px;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="text-center" style="color: darkslategrey;"><b>Title</b></h4>


                                </div>
                                <div class="modal-body" style="padding:40px 5px;">
                                    <p>
                                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </p>
                                </div>

                            </div>

                        </div>
                    </div>
            <!--End Modal-->


        </div>
        </div>
            {% endfor %}
        {% endif %}



    </div>
    <!-- End of Blog -->

<!-- Location & contact form -->
    <div class="row">
        <div class="page-header">
            <h3 class="text-center text-primary text-head"><b>Get in Touch</b></h3>
        </div>
        <div class="col-md-6 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <p class="lead1">Drop A Message...</p>
            <hr>

                <form name="conatact_form" method="POST" action="mailto:kimeualexis@gmail.com">
                    <div class="form-group">
                        <label for="name" id="form">Name:<span style="color:red;">*</span></label>
                        <input type="text" class="form-control form-control-lg" id="forme" required>
                        <br>

                        <label for="email" id="form">Email:<span style="color:red;">*</span></label>
                        <input type="email" class="form-control form-control-lg" id="forme" required>
                        <br>

                        <label for="subject" id="form">Subject:<span style="color:red;">*</span></label>
                        <input type="text" class="form-control" id="forme" required>
                        <br>
                        <label for="message" id="form">Message:<span style="color:red;">*</span></label>
                        <textarea class="form-control" id="textarea" rows="7" required></textarea>
                        <br>
                        <button type="submit" class="btn btn-success">Send Message</button>
                    </div>
                </form>
            </div>


            <div class="col-md-6 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <p class="lead1">Find Us...</p>
                <hr>

                <div class="col-md-6 text-center">
                    <br>
                    <br>
                    <i class="fa fa-map-marker fa-4x"></i>
                    <h4>Address/Street:</h4>
                    <p id="acts">P.O BOX: 1213-00618</p>
                    <p id="acts">Ngara, <br> Nairobi</p>
                </div>
                <div class="col-md-6 text-center">
                    <br>
                    <br>
                    <i class="fa fa-mobile fa-4x"></i>
                    <h4>Phone Number:</h4>
                    <p id="acts">+254(0723494571)</p>
                </div>

                <div class="col-md-12">
                    <br>
                    <br>
                    <br>
                    <hr>
                    <p class="text-center" id="acts">
                        When the whole world is watched, filed, indexed, numbered...the only way to disappear is to appear.
                    </p>
                    <p class="text-center" id="italic">~Root-POI</p>
                </div>
            </div>


        </div>


    </div>

    <!-- End location & contact section-->


</div>
    {% include 'schapp/footer.html' %}
    <script src="{% static 'schapp/js/main.js' %}"></script>
{% endblock %}

schapp/templates/schapp/sports.html
{% extends 'schapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
    <div class="banner-img">
    <img src="{% static 'schapp/img/depart.jpg' %}" alt="" style="width: 100%; padding-top: 30px; height: 40%;">

        <div class="page-header">
            <h1 class="text-center text-primary"> <strong>Sports</strong></h1>
        </div>
    </div>
</div>

    <br>
        {% if games %}
            {% for g in games %}
    <div class="col-sm-3">
        <div class="panel panel-primary">
            <div class="" style="padding-left: 18px;">
                <h3>{{ g.name }}</h3>
                <p></p>
            </div>
            <div class="panel-body" style="height: 33%;">
                <p>{{ g.desc }}</p>
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" style="margin: 4px;">More</button>

                <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="padding:5px 5px;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="text-center" style="color: darkslategrey;"><b>{{ c.name }}</b></h4>


                                </div>
                                <div class="modal-body" style="padding:40px 5px;">
                                    <p>{{ c.desc }}</p>
                                </div>

                            </div>

                        </div>
                    </div>
            <!--End Modal-->

            </div>
        </div>
    </div>
            {% endfor %}
    {% endif %}





    </div>
    <script src="{% static 'schapp/js/main.js' %}"></script>
    {% include 'schapp/footer.html' %}

{% endblock %}